### ISSUE TITLE
Dodanie opisu help - część III: 

### ISSUE THREAD

**Issue by jjustynaa** [jjustynaa/npg_kalkulator#26]
Należy dodać opisy do funkcji help następujących rzeczy:

- obliczenia zaokrągleń liczb
- obliczanie funkcji trygonometrycznych
- obliczenie funkcji cyklometrycznych 
- obliczanie liczb zespolonych

**Comment by M-GENEROWICZ** [comment]
Opis został dodany przed utworzeniem zadanie
